server:
  port: 8080

spring:
  application:
    name: patrimonium

  mail:
    host: smtp.gmail.com
    port: 587
    username: seu_email@gmail.com
    password: sua_senha_app
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/patrimonium
    username: postgres
    password: Mt190720@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # NUNCA update em projeto sério
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
security:
  jwt:
    secret: ftC7FNJuEQPqjUJU59QC7f4zWhXX9BlBZnJQx7xMvpJUa3odVx+D91UZF5pKT9RVGsHvnxrwnJhO7xLAP9vv7w==
    expiration: 86400000 # 24h em ms
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always