ALTER TABLE properties
ADD COLUMN categorry VARCHAR(50),

ADD COLUMN number VARCHAR(5),
ADD COLUMN city VARCHAR(100),
ADD COLUMN state VARCHAR(2),
ADD COLUMN zip_code VARCHAR(20),

ADD COLUMN bedrooms INT,
ADD COLUMN bathrooms INT,
ADD COLUMN suites INT,
ADD COLUMN parking_spots INT,

ADD COLUMN total_area NUMERIC(10,2),
ADD COLUMN built_area NUMERIC(10,2),
ADD COLUMN floor INT,
ADD COLUMN furnished BOOLEAN DEFAULT FALSE,

ADD COLUMN description TEXT,

ADD COLUMN estimated_value NUMERIC(15,2),
ADD COLUMN rent_value NUMERIC(15,2);
ADD COLUMN condo_fee NUMERIC(15,2);
ADD COLUMN iptu NUMERIC(15,2);

ADD COLUMN active BOOLEAN DEFAULT TRUE,
ADD COLUMN available_for_rent BOOLEAN DEFAULT FALSE,
ADD COLUMN available_for_sale BOOLEAN DEFAULT FALSE,

updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,